steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ksat-math-ai:$COMMIT_SHA', '.']
  
  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ksat-math-ai:$COMMIT_SHA']
  
  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ksat-math-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ksat-math-ai:$COMMIT_SHA'
      - '--region'
      - 'asia-northeast3'  # 서울 리전
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--set-env-vars'
      - 'GEMINI_API_KEY=${_GEMINI_API_KEY}'

# 이미지 태깅
images:
  - 'gcr.io/$PROJECT_ID/ksat-math-ai:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/ksat-math-ai:latest'

# 빌드 옵션
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# 대체 변수 (Cloud Build 트리거에서 설정)
substitutions:
  _GEMINI_API_KEY: ''  # Cloud Build 트리거에서 설정